const countries = [
  {
    countryName: "Andorra",
    countryCode: "AD",
    countryRegion: "Europe",
    countryFlag: "🇦🇩",
  },
  {
    countryName: "Afghanistan",
    countryCode: "AF",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇦🇫",
  },
  {
    countryName: "Antigua and Barbuda",
    countryCode: "AG",
    countryRegion: "South/Latin America",
    countryFlag: "🇦🇬",
  },
  {
    countryName: "Anguilla",
    countryCode: "AI",
    countryRegion: "South/Latin America",
    countryFlag: "🇦🇮",
  },
  {
    countryName: "Albania",
    countryCode: "AL",
    countryRegion: "Europe",
    countryFlag: "🇦🇱",
  },
  {
    countryName: "Armenia",
    countryCode: "AM",
    countryRegion: "Europe",
    countryFlag: "🇦🇲",
  },
  {
    countryName: "Angola",
    countryCode: "AO",
    countryRegion: "Africa",
    countryFlag: "🇦🇴",
  },
  {
    countryName: "Antarctica",
    countryCode: "AQ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇦🇶",
  },
  {
    countryName: "Argentina",
    countryCode: "AR",
    countryRegion: "South/Latin America",
    countryFlag: "🇦🇷",
  },
  {
    countryName: "American Samoa",
    countryCode: "AS",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇦🇸",
  },
  {
    countryName: "Austria",
    countryCode: "AT",
    countryRegion: "Europe",
    countryFlag: "🇦🇹",
  },
  {
    countryName: "Australia",
    countryCode: "AU",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇦🇺",
  },
  {
    countryName: "Aruba",
    countryCode: "AW",
    countryRegion: "South/Latin America",
    countryFlag: "🇦🇼",
  },
  {
    countryName: "Åland Islands",
    countryCode: "AX",
    countryRegion: "Europe",
    countryFlag: "🇦🇽",
  },
  {
    countryName: "Azerbaijan",
    countryCode: "AZ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇦🇿",
  },
  {
    countryName: "Bosnia and Herzegovina",
    countryCode: "BA",
    countryRegion: "Europe",
    countryFlag: "🇧🇦",
  },
  {
    countryName: "Barbados",
    countryCode: "BB",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇧",
  },
  {
    countryName: "Bangladesh",
    countryCode: "BD",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇧🇩",
  },
  {
    countryName: "Belgium",
    countryCode: "BE",
    countryRegion: "Europe",
    countryFlag: "🇧🇪",
  },
  {
    countryName: "Burkina Faso",
    countryCode: "BF",
    countryRegion: "Africa",
    countryFlag: "🇧🇫",
  },
  {
    countryName: "Bulgaria",
    countryCode: "BG",
    countryRegion: "Europe",
    countryFlag: "🇧🇬",
  },
  {
    countryName: "Bahrain",
    countryCode: "BH",
    countryRegion: "Arab States",
    countryFlag: "🇧🇭",
  },
  {
    countryName: "Burundi",
    countryCode: "BI",
    countryRegion: "Africa",
    countryFlag: "🇧🇮",
  },
  {
    countryName: "Benin",
    countryCode: "BJ",
    countryRegion: "Africa",
    countryFlag: "🇧🇯",
  },
  {
    countryName: "Saint Barthélemy",
    countryCode: "BL",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇱",
  },
  {
    countryName: "Bermuda",
    countryCode: "BM",
    countryRegion: "North America",
    countryFlag: "🇧🇲",
  },
  {
    countryName: "Brunei Darussalam",
    countryCode: "BN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇧🇳",
  },
  {
    countryName: "Bolivia (Plurinational State of)",
    countryCode: "BO",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇴",
  },
  {
    countryName: "Bonaire, Sint Eustatius and Saba",
    countryCode: "BQ",
    countryRegion: "Unknown",
    countryFlag: "🇧🇶",
  },
  {
    countryName: "Brazil",
    countryCode: "BR",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇷",
  },
  {
    countryName: "Bhutan",
    countryCode: "BT",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇧🇹",
  },
  {
    countryName: "Bouvet Island",
    countryCode: "BV",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇻",
  },
  {
    countryName: "Botswana",
    countryCode: "BW",
    countryRegion: "Africa",
    countryFlag: "🇧🇼",
  },
  {
    countryName: "Belarus",
    countryCode: "BY",
    countryRegion: "Europe",
    countryFlag: "🇧🇾",
  },
  {
    countryName: "Belize",
    countryCode: "BZ",
    countryRegion: "South/Latin America",
    countryFlag: "🇧🇿",
  },
  {
    countryName: "Canada",
    countryCode: "CA",
    countryRegion: "North America",
    countryFlag: "🇨🇦",
  },
  {
    countryName: "Switzerland",
    countryCode: "CH",
    countryRegion: "Europe",
    countryFlag: "🇨🇭",
  },
  {
    countryName: "Côte d'Ivoire",
    countryCode: "CI",
    countryRegion: "Africa",
    countryFlag: "🇨🇮",
  },
  {
    countryName: "Chile",
    countryCode: "CL",
    countryRegion: "South/Latin America",
    countryFlag: "🇨🇱",
  },
  {
    countryName: "Cameroon",
    countryCode: "CM",
    countryRegion: "Africa",
    countryFlag: "🇨🇲",
  },
  {
    countryName: "China",
    countryCode: "CN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇨🇳",
  },
  {
    countryName: "Colombia",
    countryCode: "CO",
    countryRegion: "South/Latin America",
    countryFlag: "🇨🇴",
  },
  {
    countryName: "Costa Rica",
    countryCode: "CR",
    countryRegion: "South/Latin America",
    countryFlag: "🇨🇷",
  },
  {
    countryName: "Cuba",
    countryCode: "CU",
    countryRegion: "South/Latin America",
    countryFlag: "🇨🇺",
  },
  {
    countryName: "Cabo Verde",
    countryCode: "CV",
    countryRegion: "Africa",
    countryFlag: "🇨🇻",
  },
  {
    countryName: "Curaçao",
    countryCode: "CW",
    countryRegion: "Unknown",
    countryFlag: "🇨🇼",
  },
  {
    countryName: "Christmas Island",
    countryCode: "CX",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇨🇽",
  },
  {
    countryName: "Cyprus",
    countryCode: "CY",
    countryRegion: "Europe",
    countryFlag: "🇨🇾",
  },
  {
    countryName: "Germany",
    countryCode: "DE",
    countryRegion: "Europe",
    countryFlag: "🇩🇪",
  },
  {
    countryName: "Djibouti",
    countryCode: "DJ",
    countryRegion: "Arab States",
    countryFlag: "🇩🇯",
  },
  {
    countryName: "Denmark",
    countryCode: "DK",
    countryRegion: "Europe",
    countryFlag: "🇩🇰",
  },
  {
    countryName: "Dominica",
    countryCode: "DM",
    countryRegion: "South/Latin America",
    countryFlag: "🇩🇲",
  },
  {
    countryName: "Algeria",
    countryCode: "DZ",
    countryRegion: "Arab States",
    countryFlag: "🇩🇿",
  },
  {
    countryName: "Ecuador",
    countryCode: "EC",
    countryRegion: "South/Latin America",
    countryFlag: "🇪🇨",
  },
  {
    countryName: "Estonia",
    countryCode: "EE",
    countryRegion: "Europe",
    countryFlag: "🇪🇪",
  },
  {
    countryName: "Egypt",
    countryCode: "EG",
    countryRegion: "Arab States",
    countryFlag: "🇪🇬",
  },
  {
    countryName: "Western Sahara",
    countryCode: "EH",
    countryRegion: "Africa",
    countryFlag: "🇪🇭",
  },
  {
    countryName: "Eritrea",
    countryCode: "ER",
    countryRegion: "Africa",
    countryFlag: "🇪🇷",
  },
  {
    countryName: "Spain",
    countryCode: "ES",
    countryRegion: "Europe",
    countryFlag: "🇪🇸",
  },
  {
    countryName: "Ethiopia",
    countryCode: "ET",
    countryRegion: "Africa",
    countryFlag: "🇪🇹",
  },
  {
    countryName: "Finland",
    countryCode: "FI",
    countryRegion: "Europe",
    countryFlag: "🇫🇮",
  },
  {
    countryName: "Fiji",
    countryCode: "FJ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇫🇯",
  },
  {
    countryName: "Micronesia (Federated States of)",
    countryCode: "FM",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇫🇲",
  },
  {
    countryName: "France",
    countryCode: "FR",
    countryRegion: "Europe",
    countryFlag: "🇫🇷",
  },
  {
    countryName: "Gabon",
    countryCode: "GA",
    countryRegion: "Africa",
    countryFlag: "🇬🇦",
  },
  {
    countryName: "Grenada",
    countryCode: "GD",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇩",
  },
  {
    countryName: "Georgia",
    countryCode: "GE",
    countryRegion: "Europe",
    countryFlag: "🇬🇪",
  },
  {
    countryName: "French Guiana",
    countryCode: "GF",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇫",
  },
  {
    countryName: "Guernsey",
    countryCode: "GG",
    countryRegion: "Europe",
    countryFlag: "🇬🇬",
  },
  {
    countryName: "Ghana",
    countryCode: "GH",
    countryRegion: "Africa",
    countryFlag: "🇬🇭",
  },
  {
    countryName: "Gibraltar",
    countryCode: "GI",
    countryRegion: "Europe",
    countryFlag: "🇬🇮",
  },
  {
    countryName: "Greenland",
    countryCode: "GL",
    countryRegion: "Europe",
    countryFlag: "🇬🇱",
  },
  {
    countryName: "Guinea",
    countryCode: "GN",
    countryRegion: "Africa",
    countryFlag: "🇬🇳",
  },
  {
    countryName: "Guadeloupe",
    countryCode: "GP",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇵",
  },
  {
    countryName: "Equatorial Guinea",
    countryCode: "GQ",
    countryRegion: "Africa",
    countryFlag: "🇬🇶",
  },
  {
    countryName: "Greece",
    countryCode: "GR",
    countryRegion: "Europe",
    countryFlag: "🇬🇷",
  },
  {
    countryName: "South Georgia and the South Sandwich Islands",
    countryCode: "GS",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇸",
  },
  {
    countryName: "Guatemala",
    countryCode: "GT",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇹",
  },
  {
    countryName: "Guam",
    countryCode: "GU",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇬🇺",
  },
  {
    countryName: "Guinea-Bissau",
    countryCode: "GW",
    countryRegion: "Africa",
    countryFlag: "🇬🇼",
  },
  {
    countryName: "Guyana",
    countryCode: "GY",
    countryRegion: "South/Latin America",
    countryFlag: "🇬🇾",
  },
  {
    countryName: "Hong Kong",
    countryCode: "HK",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇭🇰",
  },
  {
    countryName: "Honduras",
    countryCode: "HN",
    countryRegion: "South/Latin America",
    countryFlag: "🇭🇳",
  },
  {
    countryName: "Croatia",
    countryCode: "HR",
    countryRegion: "Europe",
    countryFlag: "🇭🇷",
  },
  {
    countryName: "Haiti",
    countryCode: "HT",
    countryRegion: "South/Latin America",
    countryFlag: "🇭🇹",
  },
  {
    countryName: "Hungary",
    countryCode: "HU",
    countryRegion: "Europe",
    countryFlag: "🇭🇺",
  },
  {
    countryName: "Indonesia",
    countryCode: "ID",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇮🇩",
  },
  {
    countryName: "Ireland",
    countryCode: "IE",
    countryRegion: "Europe",
    countryFlag: "🇮🇪",
  },
  {
    countryName: "Israel",
    countryCode: "IL",
    countryRegion: "Europe",
    countryFlag: "🇮🇱",
  },
  {
    countryName: "Isle of Man",
    countryCode: "IM",
    countryRegion: "Europe",
    countryFlag: "🇮🇲",
  },
  {
    countryName: "India",
    countryCode: "IN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇮🇳",
  },
  {
    countryName: "Iraq",
    countryCode: "IQ",
    countryRegion: "Arab States",
    countryFlag: "🇮🇶",
  },
  {
    countryName: "Iran (Islamic Republic of)",
    countryCode: "IR",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇮🇷",
  },
  {
    countryName: "Iceland",
    countryCode: "IS",
    countryRegion: "Europe",
    countryFlag: "🇮🇸",
  },
  {
    countryName: "Italy",
    countryCode: "IT",
    countryRegion: "Europe",
    countryFlag: "🇮🇹",
  },
  {
    countryName: "Jersey",
    countryCode: "JE",
    countryRegion: "Europe",
    countryFlag: "🇯🇪",
  },
  {
    countryName: "Jamaica",
    countryCode: "JM",
    countryRegion: "South/Latin America",
    countryFlag: "🇯🇲",
  },
  {
    countryName: "Jordan",
    countryCode: "JO",
    countryRegion: "Arab States",
    countryFlag: "🇯🇴",
  },
  {
    countryName: "Japan",
    countryCode: "JP",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇯🇵",
  },
  {
    countryName: "Kenya",
    countryCode: "KE",
    countryRegion: "Africa",
    countryFlag: "🇰🇪",
  },
  {
    countryName: "Kyrgyzstan",
    countryCode: "KG",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇰🇬",
  },
  {
    countryName: "Cambodia",
    countryCode: "KH",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇰🇭",
  },
  {
    countryName: "North Korea",
    countryCode: "KP",
    countryRegion: "Asia",
    countryFlag: "🇰🇵",
  },
  {
    countryName: "South Korea",
    countryCode: "KR",
    countryRegion: "Asia",
    countryFlag: "🇰🇷",
  },
  {
    countryName: "Kiribati",
    countryCode: "KI",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇰🇮",
  },
  {
    countryName: "Saint Kitts and Nevis",
    countryCode: "KN",
    countryRegion: "South/Latin America",
    countryFlag: "🇰🇳",
  },
  {
    countryName: "Kuwait",
    countryCode: "KW",
    countryRegion: "Arab States",
    countryFlag: "🇰🇼",
  },
  {
    countryName: "Kazakhstan",
    countryCode: "KZ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇰🇿",
  },
  {
    countryName: "Lebanon",
    countryCode: "LB",
    countryRegion: "Arab States",
    countryFlag: "🇱🇧",
  },
  {
    countryName: "Saint Lucia",
    countryCode: "LC",
    countryRegion: "South/Latin America",
    countryFlag: "🇱🇨",
  },
  {
    countryName: "Liechtenstein",
    countryCode: "LI",
    countryRegion: "Europe",
    countryFlag: "🇱🇮",
  },
  {
    countryName: "Sri Lanka",
    countryCode: "LK",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇱🇰",
  },
  {
    countryName: "Liberia",
    countryCode: "LR",
    countryRegion: "Africa",
    countryFlag: "🇱🇷",
  },
  {
    countryName: "Lesotho",
    countryCode: "LS",
    countryRegion: "Africa",
    countryFlag: "🇱🇸",
  },
  {
    countryName: "Lithuania",
    countryCode: "LT",
    countryRegion: "Europe",
    countryFlag: "🇱🇹",
  },
  {
    countryName: "Luxembourg",
    countryCode: "LU",
    countryRegion: "Europe",
    countryFlag: "🇱🇺",
  },
  {
    countryName: "Latvia",
    countryCode: "LV",
    countryRegion: "Europe",
    countryFlag: "🇱🇻",
  },
  {
    countryName: "Libya",
    countryCode: "LY",
    countryRegion: "Arab States",
    countryFlag: "🇱🇾",
  },
  {
    countryName: "Morocco",
    countryCode: "MA",
    countryRegion: "Arab States",
    countryFlag: "🇲🇦",
  },
  {
    countryName: "Monaco",
    countryCode: "MC",
    countryRegion: "Europe",
    countryFlag: "🇲🇨",
  },
  {
    countryName: "Montenegro",
    countryCode: "ME",
    countryRegion: "Europe",
    countryFlag: "🇲🇪",
  },
  {
    countryName: "Saint Martin (French part)",
    countryCode: "MF",
    countryRegion: "South/Latin America",
    countryFlag: "🇲🇫",
  },
  {
    countryName: "Madagascar",
    countryCode: "MG",
    countryRegion: "Africa",
    countryFlag: "🇲🇬",
  },
  {
    countryName: "Mali",
    countryCode: "ML",
    countryRegion: "Africa",
    countryFlag: "🇲🇱",
  },
  {
    countryName: "Myanmar",
    countryCode: "MM",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇲🇲",
  },
  {
    countryName: "Mongolia",
    countryCode: "MN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇲🇳",
  },
  {
    countryName: "Macao",
    countryCode: "MO",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇲🇴",
  },
  {
    countryName: "Martinique",
    countryCode: "MQ",
    countryRegion: "South/Latin America",
    countryFlag: "🇲🇶",
  },
  {
    countryName: "Mauritania",
    countryCode: "MR",
    countryRegion: "Arab States",
    countryFlag: "🇲🇷",
  },
  {
    countryName: "Montserrat",
    countryCode: "MS",
    countryRegion: "South/Latin America",
    countryFlag: "🇲🇸",
  },
  {
    countryName: "Malta",
    countryCode: "MT",
    countryRegion: "Europe",
    countryFlag: "🇲🇹",
  },
  {
    countryName: "Mauritius",
    countryCode: "MU",
    countryRegion: "Africa",
    countryFlag: "🇲🇺",
  },
  {
    countryName: "Maldives",
    countryCode: "MV",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇲🇻",
  },
  {
    countryName: "Malawi",
    countryCode: "MW",
    countryRegion: "Africa",
    countryFlag: "🇲🇼",
  },
  {
    countryName: "Mexico",
    countryCode: "MX",
    countryRegion: "South/Latin America",
    countryFlag: "🇲🇽",
  },
  {
    countryName: "Malaysia",
    countryCode: "MY",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇲🇾",
  },
  {
    countryName: "Mozambique",
    countryCode: "MZ",
    countryRegion: "Africa",
    countryFlag: "🇲🇿",
  },
  {
    countryName: "Namibia",
    countryCode: "NA",
    countryRegion: "Africa",
    countryFlag: "🇳🇦",
  },
  {
    countryName: "New Caledonia",
    countryCode: "NC",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇨",
  },
  {
    countryName: "Norfolk Island",
    countryCode: "NF",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇫",
  },
  {
    countryName: "Nigeria",
    countryCode: "NG",
    countryRegion: "Africa",
    countryFlag: "🇳🇬",
  },
  {
    countryName: "Nicaragua",
    countryCode: "NI",
    countryRegion: "South/Latin America",
    countryFlag: "🇳🇮",
  },
  {
    countryName: "Norway",
    countryCode: "NO",
    countryRegion: "Europe",
    countryFlag: "🇳🇴",
  },
  {
    countryName: "Nepal",
    countryCode: "NP",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇵",
  },
  {
    countryName: "Nauru",
    countryCode: "NR",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇷",
  },
  {
    countryName: "Niue",
    countryCode: "NU",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇺",
  },
  {
    countryName: "New Zealand",
    countryCode: "NZ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇳🇿",
  },
  {
    countryName: "Oman",
    countryCode: "OM",
    countryRegion: "Arab States",
    countryFlag: "🇴🇲",
  },
  {
    countryName: "Panama",
    countryCode: "PA",
    countryRegion: "South/Latin America",
    countryFlag: "🇵🇦",
  },
  {
    countryName: "Peru",
    countryCode: "PE",
    countryRegion: "South/Latin America",
    countryFlag: "🇵🇪",
  },
  {
    countryName: "French Polynesia",
    countryCode: "PF",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇫",
  },
  {
    countryName: "Papua New Guinea",
    countryCode: "PG",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇬",
  },
  {
    countryName: "Pakistan",
    countryCode: "PK",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇰",
  },
  {
    countryName: "Poland",
    countryCode: "PL",
    countryRegion: "Europe",
    countryFlag: "🇵🇱",
  },
  {
    countryName: "Saint Pierre and Miquelon",
    countryCode: "PM",
    countryRegion: "North America",
    countryFlag: "🇵🇲",
  },
  {
    countryName: "Pitcairn",
    countryCode: "PN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇳",
  },
  {
    countryName: "Puerto Rico",
    countryCode: "PR",
    countryRegion: "South/Latin America",
    countryFlag: "🇵🇷",
  },
  {
    countryName: "Palestine, State of",
    countryCode: "PS",
    countryRegion: "Arab States",
    countryFlag: "🇵🇸",
  },
  {
    countryName: "Portugal",
    countryCode: "PT",
    countryRegion: "Europe",
    countryFlag: "🇵🇹",
  },
  {
    countryName: "Palau",
    countryCode: "PW",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇼",
  },
  {
    countryName: "Paraguay",
    countryCode: "PY",
    countryRegion: "South/Latin America",
    countryFlag: "🇵🇾",
  },
  {
    countryName: "Qatar",
    countryCode: "QA",
    countryRegion: "Arab States",
    countryFlag: "🇶🇦",
  },
  {
    countryName: "Réunion",
    countryCode: "RE",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇷🇪",
  },
  {
    countryName: "Romania",
    countryCode: "RO",
    countryRegion: "Europe",
    countryFlag: "🇷🇴",
  },
  {
    countryName: "Serbia",
    countryCode: "RS",
    countryRegion: "Europe",
    countryFlag: "🇷🇸",
  },
  {
    countryName: "Russia",
    countryCode: "RU",
    countryRegion: "Europe",
    countryFlag: "🇷🇺",
  },
  {
    countryName: "Rwanda",
    countryCode: "RW",
    countryRegion: "Africa",
    countryFlag: "🇷🇼",
  },
  {
    countryName: "Saudi Arabia",
    countryCode: "SA",
    countryRegion: "Arab States",
    countryFlag: "🇸🇦",
  },
  {
    countryName: "Solomon Islands",
    countryCode: "SB",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇸🇧",
  },
  {
    countryName: "Seychelles",
    countryCode: "SC",
    countryRegion: "Africa",
    countryFlag: "🇸🇨",
  },
  {
    countryName: "Sweden",
    countryCode: "SE",
    countryRegion: "Europe",
    countryFlag: "🇸🇪",
  },
  {
    countryName: "Singapore",
    countryCode: "SG",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇸🇬",
  },
  {
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    countryCode: "SH",
    countryRegion: "Africa",
    countryFlag: "🇸🇭",
  },
  {
    countryName: "Slovenia",
    countryCode: "SI",
    countryRegion: "Europe",
    countryFlag: "🇸🇮",
  },
  {
    countryName: "Svalbard and Jan Mayen",
    countryCode: "SJ",
    countryRegion: "Europe",
    countryFlag: "🇸🇯",
  },
  {
    countryName: "Slovakia",
    countryCode: "SK",
    countryRegion: "Europe",
    countryFlag: "🇸🇰",
  },
  {
    countryName: "Sierra Leone",
    countryCode: "SL",
    countryRegion: "Africa",
    countryFlag: "🇸🇱",
  },
  {
    countryName: "Republic of San Marino",
    countryCode: "SM",
    countryRegion: "Europe",
    countryFlag: "🇸🇲",
  },
  {
    countryName: "Senegal",
    countryCode: "SN",
    countryRegion: "Africa",
    countryFlag: "🇸🇳",
  },
  {
    countryName: "Somalia",
    countryCode: "SO",
    countryRegion: "Arab States",
    countryFlag: "🇸🇴",
  },
  {
    countryName: "Suriname",
    countryCode: "SR",
    countryRegion: "South/Latin America",
    countryFlag: "🇸🇷",
  },
  {
    countryName: "South Sudan",
    countryCode: "SS",
    countryRegion: "Africa",
    countryFlag: "🇸🇸",
  },
  {
    countryName: "Sao Tome and Principe",
    countryCode: "ST",
    countryRegion: "Africa",
    countryFlag: "🇸🇹",
  },
  {
    countryName: "El Salvador",
    countryCode: "SV",
    countryRegion: "South/Latin America",
    countryFlag: "🇸🇻",
  },
  {
    countryName: "Sint Maarten (Dutch part)",
    countryCode: "SX",
    countryRegion: "Unknown",
    countryFlag: "🇸🇽",
  },
  {
    countryName: "Syrian Arab Republic",
    countryCode: "SY",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇸🇾",
  },
  {
    countryName: "Chad",
    countryCode: "TD",
    countryRegion: "Africa",
    countryFlag: "🇹🇩",
  },
  {
    countryName: "Togo",
    countryCode: "TG",
    countryRegion: "Africa",
    countryFlag: "🇹🇬",
  },
  {
    countryName: "Thailand",
    countryCode: "TH",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇭",
  },
  {
    countryName: "Tajikistan",
    countryCode: "TJ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇯",
  },
  {
    countryName: "Tokelau",
    countryCode: "TK",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇰",
  },
  {
    countryName: "Timor-Leste",
    countryCode: "TL",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇱",
  },
  {
    countryName: "Turkmenistan",
    countryCode: "TM",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇲",
  },
  {
    countryName: "Tunisia",
    countryCode: "TN",
    countryRegion: "Arab States",
    countryFlag: "🇹🇳",
  },
  {
    countryName: "Tonga",
    countryCode: "TO",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇴",
  },
  {
    countryName: "Turkey",
    countryCode: "TR",
    countryRegion: "Europe",
    countryFlag: "🇹🇷",
  },
  {
    countryName: "Trinidad and Tobago",
    countryCode: "TT",
    countryRegion: "South/Latin America",
    countryFlag: "🇹🇹",
  },
  {
    countryName: "Tuvalu",
    countryCode: "TV",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇻",
  },
  {
    countryName: "United Republic of Tanzania",
    countryCode: "TZ",
    countryRegion: "Africa",
    countryFlag: "🇹🇿",
  },
  {
    countryName: "Ukraine",
    countryCode: "UA",
    countryRegion: "Europe",
    countryFlag: "🇺🇦",
  },
  {
    countryName: "Uganda",
    countryCode: "UG",
    countryRegion: "Africa",
    countryFlag: "🇺🇬",
  },
  {
    countryName: "United States of America",
    countryCode: "US",
    countryRegion: "North America",
    countryFlag: "🇺🇸",
  },
  {
    countryName: "Uruguay",
    countryCode: "UY",
    countryRegion: "South/Latin America",
    countryFlag: "🇺🇾",
  },
  {
    countryName: "Uzbekistan",
    countryCode: "UZ",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇺🇿",
  },
  {
    countryName: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    countryRegion: "South/Latin America",
    countryFlag: "🇻🇨",
  },
  {
    countryName: "Venezuela (Bolivarian Republic of)",
    countryCode: "VE",
    countryRegion: "South/Latin America",
    countryFlag: "🇻🇪",
  },
  {
    countryName: "Virgin Islands (British)",
    countryCode: "VG",
    countryRegion: "South/Latin America",
    countryFlag: "🇻🇬",
  },
  {
    countryName: "Virgin Islands (U.S.)",
    countryCode: "VI",
    countryRegion: "South/Latin America",
    countryFlag: "🇻🇮",
  },
  {
    countryName: "Vietnam",
    countryCode: "VN",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇻🇳",
  },
  {
    countryName: "Vanuatu",
    countryCode: "VU",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇻🇺",
  },
  {
    countryName: "Wallis and Futuna",
    countryCode: "WF",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇼🇫",
  },
  {
    countryName: "Samoa",
    countryCode: "WS",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇼🇸",
  },
  {
    countryName: "Yemen",
    countryCode: "YE",
    countryRegion: "Arab States",
    countryFlag: "🇾🇪",
  },
  {
    countryName: "Mayotte",
    countryCode: "YT",
    countryRegion: "Africa",
    countryFlag: "🇾🇹",
  },
  {
    countryName: "South Africa",
    countryCode: "ZA",
    countryRegion: "Africa",
    countryFlag: "🇿🇦",
  },
  {
    countryName: "Zambia",
    countryCode: "ZM",
    countryRegion: "Africa",
    countryFlag: "🇿🇲",
  },
  {
    countryName: "Zimbabwe",
    countryCode: "ZW",
    countryRegion: "Africa",
    countryFlag: "🇿🇼",
  },
  {
    countryName: "Eswatini",
    countryCode: "SZ",
    countryRegion: "Africa",
    countryFlag: "🇸🇿",
  },
  {
    countryName: "North Macedonia",
    countryCode: "MK",
    countryRegion: "Europe",
    countryFlag: "🇲🇰",
  },
  {
    countryName: "Philippines",
    countryCode: "PH",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇵🇭",
  },
  {
    countryName: "Netherlands",
    countryCode: "NL",
    countryRegion: "Europe",
    countryFlag: "🇳🇱",
  },
  {
    countryName: "United Arab Emirates",
    countryCode: "AE",
    countryRegion: "Arab States",
    countryFlag: "🇦🇪",
  },
  {
    countryName: "Republic of Moldova",
    countryCode: "MD",
    countryRegion: "Europe",
    countryFlag: "🇲🇩",
  },
  {
    countryName: "Gambia",
    countryCode: "GM",
    countryRegion: "Africa",
    countryFlag: "🇬🇲",
  },
  {
    countryName: "Dominican Republic",
    countryCode: "DO",
    countryRegion: "South/Latin America",
    countryFlag: "🇩🇴",
  },
  {
    countryName: "Sudan",
    countryCode: "SD",
    countryRegion: "Arab States",
    countryFlag: "🇸🇩",
  },
  {
    countryName: "Lao People's Democratic Republic",
    countryCode: "LA",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇱🇦",
  },
  {
    countryName: "Taiwan, Province of China",
    countryCode: "TW",
    countryRegion: "Asia & Pacific",
    countryFlag: "🇹🇼",
  },
  {
    countryName: "Republic of the Congo",
    countryCode: "CG",
    countryRegion: "Africa",
    countryFlag: "🇨🇬",
  },
  {
    countryName: "Czechia",
    countryCode: "CZ",
    countryRegion: "Europe",
    countryFlag: "🇨🇿",
  },
  {
    countryName: "United Kingdom",
    countryCode: "GB",
    countryRegion: "Europe",
    countryFlag: "🇬🇧",
  },
  {
    countryName: "Niger",
    countryCode: "NE",
    countryRegion: "Africa",
    countryFlag: "🇳🇪",
  },
  {
    countryName: "Democratic Republic of the Congo",
    countryCode: "CD",
    countryRegion: "Africa",
    countryFlag: "🇨🇩",
  },
  {
    countryName: "Commonwealth of The Bahamas",
    countryCode: "BS",
    countryRegion: "Caribbean",
    countryFlag: "🇧🇸",
  },
  {
    countryName: "Cocos (Keeling) Islands",
    countryCode: "CC",
    countryRegion: "Australia",
    countryFlag: "🇨🇨",
  },
  {
    countryName: "Central African Republic",
    countryCode: "CF",
    countryRegion: "Africa",
    countryFlag: "🇨🇫",
  },
  {
    countryName: "Cook Islands",
    countryCode: "CK",
    countryRegion: "South Pacific Ocean",
    countryFlag: "🇨🇰",
  },
  {
    countryName: "Falkland Islands",
    countryCode: "FK",
    countryRegion: "South Atlantic Ocean",
    countryFlag: "🇫🇰",
  },
  {
    countryName: "Faroe Islands",
    countryCode: "FO",
    countryRegion: "Europe",
    countryFlag: "🇫🇴",
  },
  {
    countryName: "Territory of Heard Island and McDonald Islands",
    countryCode: "HM",
    countryRegion: "Indian Ocean",
    countryFlag: "🇭🇲",
  },
  {
    countryName: "British Indian Ocean Territory",
    countryCode: "IO",
    countryRegion: "Indian Ocean",
    countryFlag: "🇮🇴",
  },
  {
    countryName: "Comoros",
    countryCode: "KM",
    countryRegion: "Indian Ocean",
    countryFlag: "🇰🇲",
  },
  {
    countryName: "Cayman Islands",
    countryCode: "KY",
    countryRegion: "Caribbean Sea",
    countryFlag: "🇰🇾",
  },
  {
    countryName: "Republic of the Marshall Islands",
    countryCode: "MH",
    countryRegion: "Pacific Ocean",
    countryFlag: "🇲🇭",
  },
  {
    countryName: "Commonwealth of the Northern Mariana Islands",
    countryCode: "MP",
    countryRegion: "Pacific Ocean",
    countryFlag: "🇲🇵",
  },
  {
    countryName: "Turks and Caicos Islands",
    countryCode: "TC",
    countryRegion: "Atlantic Ocean",
    countryFlag: "🇹🇨",
  },
  {
    countryName: "French Southern and Antarctic Lands",
    countryCode: "TF",
    countryRegion: "Indian Ocean",
    countryFlag: "🇹🇫",
  },
  {
    countryName: "United States Minor Outlying Islands",
    countryCode: "UM",
    countryRegion: "Pacific Ocean",
    countryFlag: "🇺🇲",
  },
  {
    countryName: "Holy See",
    countryCode: "VA",
    countryRegion: "Europe",
    countryFlag: "🇻🇦",
  },
  {
    countryName: "Republic of Kosovo",
    countryCode: "XK",
    countryRegion: "Europe",
    countryFlag: "🇽🇰",
  },
  {
    countryName: "Netherlands Antilles",
    countryCode: "AN",
    countryRegion: "Europe",
    countryFlag: "🇧🇶",
  },
];

const countryCodes = [
  "AD",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CH",
  "CI",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FM",
  "FR",
  "GA",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KP",
  "KR",
  "KI",
  "KN",
  "KW",
  "KZ",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "ME",
  "MF",
  "MG",
  "ML",
  "MM",
  "MN",
  "MO",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NF",
  "NG",
  "NI",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "TD",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TZ",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
  "SZ",
  "MK",
  "PH",
  "NL",
  "AE",
  "MD",
  "GM",
  "DO",
  "SD",
  "LA",
  "TW",
  "CG",
  "CZ",
  "GB",
  "NE",
  "CD",
  "BS",
  "CC",
  "CF",
  "CK",
  "FK",
  "FO",
  "HM",
  "IO",
  "KM",
  "KY",
  "MH",
  "MP",
  "TC",
  "TF",
  "UM",
  "VA",
  "XK",
  "AN",
];

module.exports = {
  countries,
  countryCodes,
};
